name: BetaTrax Local
values:
  - key: baseUrl
    value: 'http://localhost:8000'
    enabled: true
    type: default
  - key: username
    value: ''
    enabled: true
    type: default
  - key: password
    value: ''
    enabled: true
    type: default
  - key: accessToken
    value: ''
    enabled: true
    type: default
  - key: refreshToken
    value: ''
    enabled: true
    type: default
  - key: reportId
    value: 'DR-001'
    enabled: true
    type: default
  - key: devId
    value: ''
    enabled: true
    type: default
  - key: status
    value: 'ALL'
    enabled: true
    type: default
