# Generated by Django 6.0.3 on 2026-03-25 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('displayName', models.CharField()),
                ('description', models.CharField()),
                ('currentVersion', models.CharField()),
                ('isActiveBeta', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Tester',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('fullName', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField()),
                ('isActive', models.BooleanField()),
                ('productId', models.ForeignKey(default='NUL', on_delete=django.db.models.deletion.SET_DEFAULT, to='BTAPI.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOwner',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('fullName', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField()),
                ('isActive', models.BooleanField()),
                ('productId', models.ForeignKey(default='NUL', on_delete=django.db.models.deletion.SET_DEFAULT, to='BTAPI.product')),
            ],
        ),
        migrations.CreateModel(
            name='DefectReport',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField()),
                ('description', models.CharField()),
                ('reproductionSteps', models.CharField()),
                ('status', models.CharField(choices=[('NE', 'New'), ('OP', 'Open'), ('AS', 'Assigned'), ('FI', 'Fixed'), ('RE', 'Resolved')], default='NE', max_length=2)),
                ('severity', models.IntegerField(choices=[(1, 'Low'), (2, 'Minor'), (3, 'Major'), (4, 'Critical')], default=1)),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], default=1)),
                ('submittedAt', models.DateTimeField(auto_now_add=True)),
                ('testerEmail', models.EmailField(max_length=254)),
                ('assignedToId', models.ForeignKey(default='NUL', on_delete=django.db.models.deletion.SET_DEFAULT, to='BTAPI.developer')),
                ('productId', models.ForeignKey(default='NUL', on_delete=django.db.models.deletion.SET_DEFAULT, to='BTAPI.product')),
                ('evaluatedById', models.ForeignKey(default='NUL', on_delete=django.db.models.deletion.SET_DEFAULT, to='BTAPI.productowner')),
                ('testerId', models.ForeignKey(default='NUL', on_delete=django.db.models.deletion.SET_DEFAULT, to='BTAPI.tester')),
            ],
        ),
    ]
