# Generated by Django 6.0.3 on 2026-03-25 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BTAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defectreport',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('OPEN', 'Open'), ('ASSIGNED', 'Assigned'), ('FIXED', 'Fixed'), ('RESOLVED', 'Resolved')], default='NEW'),
        ),
        migrations.AlterField(
            model_name='tester',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
