# Generated by Django 6.0.3 on 2026-03-25 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BTAPI', '0002_alter_defectreport_status_alter_tester_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defectreport',
            name='testerEmail',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
