# Generated by Django 6.0.3 on 2026-03-25 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BTAPI', '0003_alter_defectreport_testeremail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='productowner',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
