# Generated by Django 6.0.3 on 2026-03-25 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BTAPI', '0004_alter_developer_email_alter_productowner_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defectreport',
            name='testerEmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='productowner',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='tester',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
