# Generated by Django 6.0.3 on 2026-03-25 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BTAPI', '0005_alter_defectreport_testeremail_alter_developer_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productowner',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
