# Generated by Django 6.0.3 on 2026-03-25 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BTAPI', '0006_alter_developer_id_alter_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defectreport',
            name='assignedToId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='BTAPI.developer'),
        ),
        migrations.AlterField(
            model_name='defectreport',
            name='evaluatedById',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='BTAPI.productowner'),
        ),
        migrations.AlterField(
            model_name='defectreport',
            name='productId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='BTAPI.product'),
        ),
        migrations.AlterField(
            model_name='defectreport',
            name='testerId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='BTAPI.tester'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='productId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='BTAPI.product'),
        ),
        migrations.AlterField(
            model_name='productowner',
            name='productId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='BTAPI.product'),
        ),
    ]
