# Generated by Django 6.0.3 on 2026-03-25 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BTAPI', '0007_alter_defectreport_assignedtoid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defectreport',
            name='assignedToId',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='BTAPI.developer'),
        ),
    ]
