# Generated by Django 6.0.3 on 2026-03-25 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BTAPI', '0010_alter_defectreport_evaluatedbyid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='productId',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='BTAPI.product'),
        ),
        migrations.AlterField(
            model_name='productowner',
            name='productId',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='BTAPI.product'),
        ),
    ]
