# Generated by Django 6.0.3 on 2026-03-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BTAPI', '0011_alter_developer_productid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defectreport',
            name='id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='developer',
            name='id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productowner',
            name='id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
