# Generated by Django 6.0.3 on 2026-03-30 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BTAPI', '0012_alter_defectreport_id_alter_developer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productowner',
            name='productId',
        ),
        migrations.AddField(
            model_name='product',
            name='ownerId',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='BTAPI.productowner'),
        ),
    ]
