# Generated by Django 6.0.3 on 2026-03-30 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BTAPI', '0013_remove_productowner_productid_product_ownerid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='productId',
        ),
        migrations.AddField(
            model_name='product',
            name='devId',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='BTAPI.developer'),
        ),
    ]
