# Generated by Django 6.0.3 on 2026-03-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BTAPI', '0014_remove_developer_productid_product_devid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defectreport',
            name='priority',
            field=models.IntegerField(blank=True, choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], null=True),
        ),
        migrations.AlterField(
            model_name='defectreport',
            name='severity',
            field=models.IntegerField(blank=True, choices=[(1, 'Low'), (2, 'Minor'), (3, 'Major'), (4, 'Critical')], null=True),
        ),
        migrations.AlterField(
            model_name='tester',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
