# Generated by Django 6.0.3 on 2026-03-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BTAPI', '0015_alter_defectreport_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='defectreport',
            name='productVersion',
            field=models.CharField(default=0.0),
            preserve_default=False,
        ),
    ]
