# Generated by Django 6.0.3 on 2026-03-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BTAPI', '0016_defectreport_productversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defectreport',
            name='priority',
            field=models.IntegerField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], null=True),
        ),
        migrations.AlterField(
            model_name='defectreport',
            name='severity',
            field=models.IntegerField(blank=True, choices=[('Low', 'Low'), ('Minor', 'Minor'), ('Major', 'Major'), ('Critical', 'Critical')], null=True),
        ),
        migrations.AlterField(
            model_name='defectreport',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Open', 'Open'), ('Assigned', 'Assigned'), ('Fixed', 'Fixed'), ('Resolved', 'Resolved')], default='New'),
        ),
    ]
