# Generated by Django 6.0.3 on 2026-03-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BTAPI', '0017_alter_defectreport_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defectreport',
            name='priority',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], null=True),
        ),
        migrations.AlterField(
            model_name='defectreport',
            name='severity',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Minor', 'Minor'), ('Major', 'Major'), ('Critical', 'Critical')], null=True),
        ),
    ]
