# Generated by Django 6.0.3 on 2026-03-31 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BTAPI', '0018_alter_defectreport_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defectreport',
            name='testerId',
            field=models.CharField(),
        ),
        migrations.RemoveField(
            model_name='defectreport',
            name='evaluatedById',
        ),
        migrations.DeleteModel(
            name='Tester',
        ),
    ]
