# Generated by Django 6.0.3 on 2026-04-05 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BTAPI', '0019_alter_defectreport_testerid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('content', models.CharField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('authorId', models.CharField()),
                ('defectReportId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='BTAPI.defectreport')),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
    ]
