# Generated by Django 6.0.3 on 2026-04-08 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BTAPI', '0020_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='defectreport',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parents', to='BTAPI.defectreport'),
        ),
        migrations.AddField(
            model_name='defectreport',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='BTAPI.defectreport'),
        ),
        migrations.AlterField(
            model_name='defectreport',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Open', 'Open'), ('Assigned', 'Assigned'), ('Closed', 'Closed'), ('Fixed', 'Fixed'), ('Reopened', 'Reopened'), ('Resolved', 'Resolved')], default='New'),
        ),
    ]
