# Generated by Django 6.0.3 on 2026-04-08 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BTAPI', '0021_defectreport_child_defectreport_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defectreport',
            name='child',
        ),
        migrations.RemoveField(
            model_name='defectreport',
            name='parent',
        ),
    ]
