# Generated by Django 6.0.3 on 2026-04-08 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BTAPI', '0022_remove_defectreport_child_remove_defectreport_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='defectreport',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parents', to='BTAPI.defectreport'),
        ),
        migrations.AddField(
            model_name='defectreport',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='BTAPI.defectreport'),
        ),
    ]
