# Generated by Django 6.0.3 on 2026-04-08 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BTAPI', '0023_defectreport_child_defectreport_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defectreport',
            name='child',
        ),
    ]
