# Generated by Django 6.0.3 on 2026-04-13 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BTAPI', '0025_alter_comment_authorid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='authorId',
            field=models.CharField(),
        ),
    ]
