# Generated by Django 6.0.3 on 2026-04-13 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BTAPI', '0026_alter_comment_authorid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defectreport',
            name='assignedToId',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='BTAPI.developer'),
        ),
        migrations.AlterField(
            model_name='defectreport',
            name='testerId',
            field=models.CharField(),
        ),
    ]
