# Generated by Django 6.0.3 on 2026-04-13 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BTAPI', '0029_alter_defectreport_assignedtoid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='authorId',
        ),
    ]
