# Generated by Django 6.0.3 on 2026-04-13 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BTAPI', '0031_comment_authorid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='authorId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorId', to=settings.AUTH_USER_MODEL),
        ),
    ]
