# Generated by Django 6.0.3 on 2026-04-13 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BTAPI', '0033_alter_defectreport_assignedtoid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defectreport',
            name='testerEmail',
        ),
        migrations.RemoveField(
            model_name='defectreport',
            name='testerId',
        ),
        migrations.AddField(
            model_name='defectreport',
            name='tester',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='defects', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
