# Generated by Django 6.0.3 on 2026-04-13 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BTAPI', '0036_alter_defectreport_tester'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defectreport',
            old_name='tester',
            new_name='testerId',
        ),
    ]
