# Generated by Django 6.0.3 on 2026-04-13 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BTAPI', '0040_alter_product_devid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='devId',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='BTAPI.developer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ownerId',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='BTAPI.productowner'),
        ),
    ]
