# Generated by Django 6.0.3 on 2026-04-13 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BTAPI', '0041_alter_product_devid_alter_product_ownerid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='devId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devId', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='ownerId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ownerId', to=settings.AUTH_USER_MODEL),
        ),
    ]
