# Generated by Django 6.0.3 on 2026-04-22 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BTAPI', '0043_alter_product_devid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductOwner',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='fullName',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='isActive',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='username',
        ),
        migrations.AddField(
            model_name='developer',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='developer_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='developer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
