# Generated by Django 6.0.3 on 2026-04-22 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BTAPI', '0044_delete_productowner_remove_developer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='fixedCount',
            field=models.IntegerField(default=0),
        ),
    ]
