# Generated by Django 6.0.3 on 2026-04-22 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BTAPI', '0045_developer_fixedcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='reopenedCount',
            field=models.IntegerField(default=0),
        ),
    ]
