# Generated by Django 6.0.3 on 2026-04-22 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BTAPI', '0046_developer_reopenedcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='fixedCount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='developer',
            name='reopenedCount',
            field=models.IntegerField(),
        ),
    ]
