# Generated by Django 6.0.3 on 2026-04-26 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BTAPI', '0048_client_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defectreport',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Open', 'Open'), ('Assigned', 'Assigned'), ('Cannot Reproduce', 'Cannot Reproduce'), ('Duplicate', 'Duplicate'), ('Rejected', 'Rejected'), ('Fixed', 'Fixed'), ('Reopened', 'Reopened'), ('Resolved', 'Resolved')], default='New'),
        ),
    ]
